DROP TABLE IF EXISTS PERSONAL_ACCOUNT CASCADE;
DROP TABLE IF EXISTS HISTORY_TRANSACTION CASCADE;

CREATE TABLE PERSONAL_ACCOUNT
(
    identification VARCHAR(20) PRIMARY KEY,
    name           VARCHAR(100)     NOT NULL,
    surname        VARCHAR(100),
    balance        DOUBLE PRECISION NOT NULL
);

CREATE TABLE HISTORY_TRANSACTION
(
    id         BIGSERIAL PRIMARY KEY,
    type       VARCHAR(20),
    amount     DOUBLE PRECISION NOT NULL,
    date       DATE             NOT NULL,
    account_id VARCHAR(20) REFERENCES PERSONAL_ACCOUNT(identification) ON DELETE CASCADE
);

